name: Publish Docker Images

on:
  push:
    tags:
      - "v*.*"

env:
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || 'aleou' }}
  DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE || 'ffmpeg-worker' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL || 'docker.io' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          docker buildx bake base final-api final-serverless --push \
            --set REGISTRY=${DOCKER_REGISTRY} \
            --set IMAGE=${DOCKER_IMAGE} \
            --set RELEASE_VERSION=${RELEASE_VERSION}
