name: Publish Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || 'aleou' }}
  DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE || 'ffmpeg-worker' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_URL || 'docker.io' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: docker buildx bake --push

